### ISSUE TITLE
Can't find Project or Library

### ISSUE THREAD

**Issue by jitendra512** [markwilliams970/RallyRestToolkitForVBA#3]
Hi Mark,

Thanks for developing this utility. I am trying to run this code. I have downloaded RallyRestTestKitForVBA. performed the following step -
1)Open RallyRestTestKitForVBA
2) Clicked on GetStories on QueryStories tab
3)Enter all the details in form and click on OK
4) I am getting below error -

Compile Error - Can't find project or library on JSON library

Private Function parseObject(ByRef str As String, ByRef index As Long) As Dictionary

Note - I have read only access for rally in my organization. Should i need to upgrade it to donwload the user story.

**Comment by markwilliams970** [comment]
Hi jltendra512 - Sometimes this may happen due to a missing loaded library. Did you make sure to load all the needed references into your VBA project as shown in this screenshot:

![RallyRestToolkitForVBA-References](https://raw.githubusercontent.com/markwilliams970/RallyRestToolkitForVBA/master/screenshots/screenshot6.png)

As outlined in the [README.md](https://github.com/markwilliams970/RallyRestToolkitForVBA/blob/master/README.md)

**Comment by jitendra512** [comment]
Hi Mark,

Thanks for your reply. I have verified the available preferences and loaded
the same references  as you mentioned in screenshot.

There is only one difference that you are using Microsoft Excel 15.0 Object
repository and I am using Microsoft Excel 14.0 object repository.

Thanks,
Jitendra

**Comment by markwilliams970** [comment]
Jitendra,

Sorry for the slow response. I've tried to reproduce the problem that you are experiencing using Excel 2010, but as of yet I cannot. Here's a video capture I took showing a successful query of stories using Excel 2010 and the Microsoft Excel 14.0 objects:

http://www.screencast.com/t/1aaBihonD

I can, however, reproduce the exact error you are seeing, if the Reference to the "Microsoft Scripting Runtime" is either un-checked, or missing/unavailable. See this video capture:

http://www.screencast.com/t/fSNce0PKIKGV

Note the error: "Compile Error - Can't find project or library on JSON library
Private Function parseObject(ByRef str As String, ByRef index As Long) As Dictionary"

is the same as yours.

Can you post a screenshot of your VBA project references? Or a video showing what happens when you open a fresh copy of RallyRestToolkitForVBA.xlsm spreadsheet, verify the references are loaded, and execute the query?

Sorry for the troubles.

Kindly,
Mark

**Comment by jitendra512** [comment]
Hi Mark,

Thank you so much for saharing the video. I got the error. I am getting - Missing :ScriptingObjectModel in refrences. Please let me know how to fix this issue. It will be great help.

Please find attached scrrenshot for same.

**Comment by jitendra512** [comment]
I have unchedk the missing reference and it worked. Thanks for your help,

**Comment by markwilliams970** [comment]
Great, Jitendra, glad you were able to get things working :)

**Comment by jitendra512** [comment]
Hi Mark,

Really I am glad that you responded on my query and things are working for
me. I have to add two more function -  1) Get the rally defects in
Excel(Download the defects for project)  2) Get the Execution
status(download Test case). Can you tell me the function name so that I can
add. I am new to rally.

**Comment by markwilliams970** [comment]
Jitendra, I'm glad you're able to work with the VBA project. I'm wondering if you know about the [Excel Add-in for Rally](https://help.rallydev.com/rally-add-excel) ? While the VBA toolkit can be used to get data out of Rally, it's really intended for coders who need to do Rally-based automations in VBA. To get Defects and TestCaseResults, you would need to write some code to do this.

Since you have a read-only username in Rally and are using this mostly for querying, I think the Excel Add-in will meet your needs. It has a nice graphical user interface to allow you to query multiple data type, including Defects, and TestCaseResults, interactively.

I hope the add-in is helpful. Let me know if you are able to get the info you need using it.

**Comment by jitendra512** [comment]
Hi Mark,
Good morning.

Thanks for creating this tool and sharing in github.
I am using Rally Rest Tool kit from long time. I am looking for some
additional functionality like import data from rally. I have to create the
report and send it to management for review. Currently I can upload the
defects to rally but can 't download the same from rally using this tool.
If you can guide me I can add this feature to current tool or if it's
already available requesting you to share with me.

Thanks,
Jitendra

**Comment by markwilliams970** [comment]
Hi Jitendra, it's certainly possible to query Defects using the VBA toolkit. I would recommend that you open the VBA developer console->Forms. Right-click on GetStoriesForm and select "View Code". The code in the QueryStories() method shows a way to query User Stories and populate the results into an Excel Worksheet. The process for Defects would be exactly analogous, you would just set the myRallyRequest.ArtifactName = "defect", and use a Fetch for fields appropriate to a Defect. I hope that helps. Thanks, Mark

**Comment by jitendra512** [comment]
Hi Mark

Good morning. Thanks for your response. I am using rally add-in to get the
data but it has very limited functionality. We are looking for some custom
report. Just for example currently we can get only one workspace record
using add in and we can't append the next work space /project record. If
you can tell me methods to get the re cord  from rally probably I can do
the coding for same. I am an automation engineer. I got the access to rally
portal but not the admin access. Looking for your help.

Thanks,
Jitendra
